### ISSUE TITLE
Support multiple includes on one line

### ISSUE THREAD

**Issue by erilot** [cmacmackin/markdown-include#11]
I've got a potential use-case that populates a requirements table using includes, like this:

 Product | Operating System | Cloud Environments | Datacenter Environments 
--- | --- | --- | ---
Product X | `{! ./prod-x-os.md !}` | `{! ./prod-x-cloud.md !}` | `{! ./prod-x-dc.md !}`
Product Y | `{! ./prod-y-os.md !}` | `{! ./prod-y-cloud.md !}` | `{! ./prod-y-dc.md !}`

markdown-include only matches first include on each line, so the above scenario doesn't work. In fact, in this example scenario, everything from the second include onward is actually lost.

How do you feel about supporting multiple matches per line?

**Comment by cmacmackin** [comment]
@sander76 Sorry for the long silence on this project. This project is not one I want to devote a huge ammount of time to, but if you put together a PR then I'll be happy to review it and make a new PyPI release.

**Comment by ZedThree** [comment]
Added in #27
