### ISSUE TITLE
Allow caller to handle exceptions

### ISSUE THREAD

**Issue by timabbott** [cmacmackin/markdown-include#15]
Thanks for the nice library!  We've been using it in Zulip (http://github.com/zulip/zulip/) in hundreds of plcaes, but one significant problem is that this library doesn't throw a proper exception in the event that the file to be included isn't present.  This makes it hard to check for typoes when using this library.  See e.g. 
https://github.com/zulip/zulip/issues/10947 for details.

Would you be willing to consider a change (at least under an option) to make this library not catch-and-print the exception for an invalid file?

**Comment by cmacmackin** [comment]
Hi, thanks for the suggestion. I've implemented this feature which can be found in the development version here on Github and will be in the next release.
