### ISSUE TITLE
Remove frontmatter from 'included' markdown files

### ISSUE THREAD

**Issue by banj** [cmacmackin/markdown-include#3]
When my markdown files contain YAML or Multi-markdown style metadata, I've found that markdown-include doesn't process it out (prehaps because of the way the replacement is handled?). Is there a way I can exclude the frontmatter from the file being imported so that only the content will replace the {!tag!}?

**Comment by cmacmackin** [comment]
At present there is no way to do this. My intention was to make this a very simple feature, similar to the `#include` macro in C that just pastes in the contents of a file. There are various other include-style plugins around and perhaps one of them can do what you want. Alternatively, you (or someone else) would be welcome to fork and extend my plugin to provide the desired functionality.

**Comment by okelet** [comment]
@banj @cmacmackin what other plugins do you refer wich support frontmatter exclusion?
