### ISSUE TITLE
sdist is missing on PyPI for 0.7.0

### ISSUE THREAD

**Issue by awvwgk** [cmacmackin/markdown-include#35]
Currently there is only a wheel on PyPI for version 0.7.0, but no sdist. For packaging this project on conda-forge it would be nice to have an sdist as well

cc @hadim

**Comment by chenrui333** [comment]
Any update on this?

**Comment by chenrui333** [comment]
ping again.

**Comment by ZedThree** [comment]
Sure, I'll add a workflow to automatically publish

**Comment by chenrui333** [comment]
Thank you!! Appreciate it!
