### ISSUE TITLE
0.7.0 release doesn't have markdown version update?

### ISSUE THREAD

**Issue by lizzyd710** [cmacmackin/markdown-include#36]
The release notes for 0.7.0 say it's been modified to work with 3.4 of markdown, making it incompatible with anything less than 3.0, but when I look in `setup.cfg` with the release tag of 0.7.0, nothing regarding dependencies changed? Was this a mistake or intentional?

**Comment by ZedThree** [comment]
Ah, the dependency was specified in `setup.py`: https://github.com/cmacmackin/markdown-include/commit/055101744b8653de116367e73c21e3f8dcee686a

It's now in `pyproject.toml`
