### ISSUE TITLE
Extension is not context aware

### ISSUE THREAD

**Issue by r0ckarong** [cmacmackin/markdown-include#4]
Not sure this is actually a bug, I can see how this is "works as designed" but might be problematic.

The intended use of the include string is "place the string somewhere and there it will include the referenced file". The problem is that if you place the string inside a code block (inline, fenced doesn't matter) to demonstrate how it is used it will process the string regardless. For an existing file you will simply get the file included at the location of the string, for a non-existing file there will be a warning.

So it's impossible to use the include string inside a code block. You can encode the braces with HTML characters outside of a code block to make an example but everything else won't work. I'm trying to teach my users how to use the extension and it breaks consistency with the rest of my examples.

**Comment by cmacmackin** [comment]
I'm not certain this will work, but have you tried escaping the curly braces with backslashes in your code block? I don't really want to turn off the plugin inside of code blocks because one potential use is to include a file of source code.

**Comment by mnapp** [comment]
Doesn't work it shows the backslashes. I was just wondering if there's a way to do this.

**Comment by kamar535** [comment]
This is exactly one of my intended use cases, to include code inside code fences where the included code is saved in a separate files that can be compiled and verified to be correct. Maybe support for this could be added to this extension or would it be a better fit for a new extension?

**Comment by neurobin** [comment]
This was one of my main motivations to write a new extension, also I wanted to be able to include remote files such as gists. Not sure if it's right to put a link here. But here it goes: [mdx_include](https://github.com/neurobin/mdx_include).

@cmacmackin  If you think it's inappropriate, you can delete my comment. It's not helping you anyway..

**Comment by cmacmackin** [comment]
This is a sufficiently uncommon case that I'm not going to change behaviour and add complexity as a result. It would be a significant breaking change to turn off inclusion inside code blocks, so the existing behaviour will remain.
