### ISSUE TITLE
Included files' tables fail rendering

### ISSUE THREAD

**Issue by ldeluigi** [cmacmackin/markdown-include#42]
Inside own file:
![image](https://user-images.githubusercontent.com/44567586/214348349-5d266293-e973-4e06-8f16-b45cf9f3d13b.png)

Inside file that includes the previous file:

![image](https://user-images.githubusercontent.com/44567586/214348702-2ce2bded-bcbe-4cac-9798-3b684e03c5d2.png)

**Comment by ZedThree** [comment]
Hi @ldeluigi, I'll try to take a look at this in the next couple of days. If you could post a minimal example of how to reproduce it here, that would really help me out.

**Comment by ldeluigi** [comment]
@ZedThree have you been able to reproduce the bug?

**Comment by ZedThree** [comment]
Thanks for the minimal example, I reproduced it in your repo using mkdocs, and then I managed to reproduce it using `markdown` directly:

```
import markdown
from markdown_include.include import MarkdownInclude

with open("README.md") as f:
    source = f.read()

html = markdown.markdown(source, extensions=["tables", MarkdownInclude(configs={"inheritHeadingDepth": True})])
print(html)
```

produces:

```html
<h1>Test</h1>
<table>
<thead>
<tr>
<th>Aaaaa</th>
<th>aaaaa</th>
<th>sdknjhdjklfhd</th>
</tr>
</thead>
<tbody>
<tr>
<td>aaa</td>
<td>aaa</td>
<td>aaaa</td>
</tr>
</tbody>
</table>
<h2>Inner title</h2>
<p>| Aaaaa | aaaaa | sdknjhdjklfhd |</p>
<p>| ----- | ----- | ------------- |</p>
<p>| aaa | aaa | aaaa |</p>
```

while passing `inheritHeadingDepth: False` gives the correct:

```html
<h1>Test</h1>
<table>
<thead>
<tr>
<th>Aaaaa</th>
<th>aaaaa</th>
<th>sdknjhdjklfhd</th>
</tr>
</thead>
<tbody>
<tr>
<td>aaa</td>
<td>aaa</td>
<td>aaaa</td>
</tr>
</tbody>
</table>
<h1>Inner title</h1>
<table>
<thead>
<tr>
<th>Aaaaa</th>
<th>aaaaa</th>
<th>sdknjhdjklfhd</th>
</tr>
</thead>
<tbody>
<tr>
<td>aaa</td>
<td>aaa</td>
<td>aaaa</td>
</tr>
</tbody>
</table>
```

So clearly something's going wrong when inheriting the header depth.

**Comment by ZedThree** [comment]
I had actually bumped into this bug before. When `inheritHeadingDepth` is `True`, then extra line breaks are added which breaks the table.

I have a fix incoming

**Comment by ZedThree** [comment]
@ldeluigi Could you check this branch: https://github.com/cmacmackin/markdown-include/tree/fix-inherit-heading-depth ?

It's possible it changes more things, so I don't want to release it just yet without some more tests.

**Comment by ldeluigi** [comment]
@ZedThree it works for me, thanks

![image](https://user-images.githubusercontent.com/44567586/217198269-7d12dd6b-dfb5-4784-9caf-d08af1fc77af.png)

**Comment by ldeluigi** [comment]
I opened a PR on your behalf
