### ISSUE TITLE
regex automatically escapes underscore at the beginning of the filename

### ISSUE THREAD

**Issue by nandordevai** [cmacmackin/markdown-include#44]
When I try to include a file with a name starting with an underscore, eg.

`{!tutorial/_setup.md!}`

I get the following error message:

`Warning: could not find file docs/tutorial/\_setup.md. Ignoring include statement. Error: [Errno 2] No such file or directory: 'docs/tutorial/\\_setup.md'`

**Comment by ZedThree** [comment]
Hi @nandordevai, sorry but I can't reproduce this locally. Could you provide a minimal complete example that demonstrates this?

**Comment by nandordevai** [comment]
Looks like it isn't a bug in markdown-include but in mkdocs. Sorry for the hasty bug report.
