### ISSUE TITLE
Extension can have infinite circular reference loop

### ISSUE THREAD

**Issue by r0ckarong** [cmacmackin/markdown-include#5]
I accidentally set up a circular reference in my page structure that brought my machine to its knees. If you include a page in itself it will endlessly try to do so (as designed).

Now, if you have multiple users like I do that use includes to build documents how can I prevent them from creating circular references? 

They might (and very likely will) include a page that unbeknownst to them includes the same page a few levels of include iterations down?

Can the extension check itself or over the "include tree" that it's parsing? If not can there be a debug message or something that tells me if this is happening?

**Comment by cmacmackin** [comment]
At present there isn't any such capability. It would be nice to add it, but I'll have to think a bit about how to do so.
